### PR TITLE
[9.100.x-prod][SRVLOGIC-325] use KogitoVersion variable for org.apache.kie.sonataflow:sonataflow-quarkus-devui version

### PR DESCRIPTION
**Pull request by rgdoliveira**
Jira: https://issues.redhat.com/browse/SRVLOGIC-325

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Review by tomasdavidorg — APPROVED** [review]

**Review by treblereel — APPROVED** [review]
It works for me. But I removed `frontend-maven-plugin` at `sonataflow-quarkus-devui/pom.xml` to make it compile. I think it's my local issue, not related with this PR

**Comment by tomasdavidorg** [comment]
> It works for me. But I removed `frontend-maven-plugin` at `sonataflow-quarkus-devui/pom.xml` to make it compile. I think it's my local issue, not related with this PR

I have the same error locally. Is there any jira for this or should I create one?

**Comment by treblereel** [comment]
@tomasdavidorg yeap, I think you can create an issue

**Comment by rgdoliveira** [comment]
Just some context related to the OSL product. 

The `frontend-maven-plugin` is added in `sonataflow-quarkus-devui/pom.xml` just in midstream (product), because we need to build (productize) the Quarkus Dev UI.  The build is done via root pom.xml created on midstream repository only which in the end invokes the `sonataflow-quarkus-devui` modules.

For building the kn workflow binary in the product, we use Brew system and we are doing an RPM build. We have a spec file in dist-git which invokes the Kn workflow Makefile (packages/kn-plugin-workflow/Makefile). For better explanation please check Jira SRVLOGIC-325.

So if a Jira would be created, I believe it should be just for the product (SRVLOGIC) as we have those differences from midstream and upstream 

(cc @mareknovotny)

**Pull request merged**
