### PR TITLE
SRVLOGIC-289: Remove workflow plugin dependency on knative/client int…

### PR DESCRIPTION
**Pull request by dsimansk**
…erface

The PR removes the interface implementation that is used for plugin embedding into `kn` directly. 

PTAL
@rgdoliveira @ricardozanini

### CODE REVIEW

**Review by treblereel — APPROVED** [review]
@dsimansk looks good to me

**Comment by dsimansk** [comment]
@treblereel btw does it need to go through ASF upstream? Or will it sync OK through midstream?

**Review by wmedvede — APPROVED** [review]
LGTM, thanks.

**Comment by wmedvede** [comment]
> @treblereel btw does it need to go through ASF upstream? Or will it sync OK through midstream?

yes, I think we need to propagate to ASF upstream too.

**Comment by treblereel** [comment]
@wmedvede yeap, let me cherry-pick it

**Pull request merged**
